# Site settings
title: Tsugi-Dev
email: your-email@domain.com
# url: https://example.github.io
url: https://dev.lrnxp.net
description: "This is a free, hosted developer instance of Tsugi.  It is reset daily at midnight Eastern. It runs the tip of the master branch of Tsugi. You can test applications on this site, learn how to administer a Tsugi instance, or use it for demonstrations."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Tsugi Developer Site

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/tsugiproject
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/tsugi
  - title: github
    url: https://github.com/tsugicloud

# Build settings
markdown: kramdown
permalink: pretty
